
export function generateAS(functions) {
    let code = `// Auto-generated by jsw
@external("env", "consoleLog")
declare function consoleLog(s: string): void;

`;

    for (const func of functions) {
        const params = func.params.map(p => `${p.name}: ${p.type}`).join(', ');
        code += `export function ${func.name}(${params}): ${func.returnType} ${func.body}\n\n`;
    }

    return code;
}
