
export function generateAS(functions, structs) {
    let code = `// Auto-generated by jsw
@external("env", "consoleLog")
declare function consoleLog(s: string): void;

`;

    const arrayTypes = new Set();

    const mapType = (t) => {
        if (t.endsWith('[]')) {
            const elem = t.slice(0, -2);
            const mappedElem = mapType(elem);
            const asType = `Array<${mappedElem}>`;
            arrayTypes.add(asType);
            return asType;
        }
        return t;
    };

    // Generate Structs
    if (structs) {
        for (const struct of structs) {
            code += `class ${struct.name} {\n`;
            for (const field of struct.fields) {
                const asType = mapType(field.type);
                let init = '';
                if (asType === 'f64' || asType === 'i32' || asType === 'u32') init = ' = 0';
                else if (asType === 'bool') init = ' = false';
                else if (asType === 'string') init = ' = ""';
                else if (asType.startsWith('Array<')) init = ` = new ${asType}(0)`;
                else init = ` = new ${asType}()`; // Structs

                code += `  ${field.name}: ${asType}${init};\n`;
            }
            code += `}\n\n`;

            // Generate helpers for marshalling
            code += `export function __new_${struct.name}(): ${struct.name} { return new ${struct.name}(); }\n`;
            code += `export function __idof_${struct.name}(): u32 { return idof<${struct.name}>(); }\n`;
            
            for (const field of struct.fields) {
                const asType = mapType(field.type);
                code += `export function __set_${struct.name}_${field.name}(obj: ${struct.name}, val: ${asType}): void { obj.${field.name} = val; }\n`;
                code += `export function __get_${struct.name}_${field.name}(obj: ${struct.name}): ${asType} { return obj.${field.name}; }\n`;
            }
            code += `\n`;
        }
    }

    for (const func of functions) {
        const params = func.params.map(p => `${p.name}: ${mapType(p.type)}`).join(', ');
        const returnType = mapType(func.returnType);
        
        code += `export function ${func.name}(${params}): ${returnType} ${func.body}\n\n`;
    }

    // Generate ID helpers for arrays
    for (const type of arrayTypes) {
        const safeName = type.replace(/[<>]/g, '_');
        code += `export function __idof_${safeName}(): u32 { return idof<${type}>(); }\n`;
    }

    return code;
}
